### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by tpimh** [bitterbit/Parse-Dashboard-Android#15]
Great open source app, but unfortunately can't find it on F-Droid. Hope that a proper F-Droid release will bring more publicity and contributors to the project.

**Comment by bitterbit** [comment]
As of today Parse Dashboard does not pass the inclusion policy of F-Droid due to the use of Crashlytics. I have no objection for replacing it with something else (or removing it). 

If anyone wants to remove it and prepare the app to be submitted to F-Droid I would be more than happy to do it.
