### ISSUE TITLE
App not available in Play Store

### ISSUE THREAD

**Issue by cyb3rko** [bitterbit/Parse-Dashboard-Android#17]
Hi,
I don't know if it's on purpose but the app is not available in the Play Store anymore.
Do you plan on making it available again?
I've just started on updating this app and I plan to add new features in the future like editing and adding entries, just like in the iOS version of this app.

Greetings

**Comment by bitterbit** [comment]
Hi Thanks for letting me know! 
its not on purpose its just google play removing old apps, Ill have a look later today and try to bring it back.

Happy to hear you are extending the app :) feel free to change anything and ask any question

**Comment by bitterbit** [comment]
I checked it and the privacy policy link got broken when I updated my personal site, I am going to update a new page with the new policy and hopefully the app will be back. 

@cyb3rko If you know a simple privacy policy template I can use it would be great

**Comment by cyb3rko** [comment]
I see.

What about this one:
https://app-privacy-policy-generator.firebaseapp.com/

I use this as well for my apps.

**Comment by bitterbit** [comment]
wow nice :)

**Comment by bitterbit** [comment]
I have created a new policy using the tool at https://galtashma.com/page/privacy-policy-parse-dashobad and sent the app to review, thanks for the help @cyb3rko

**Comment by bitterbit** [comment]
Its now back in the play store, thank you @cyb3rko for letting me know!
