### ISSUE TITLE
Does not work with server with self signed certificate

### ISSUE THREAD

**Issue by chrbayer** [bitterbit/Parse-Dashboard-Android#4]
Hi,

I can't connect to my parse server with a self signed certificate. This is most probably because of missing configuration in AndroidManifest.xml file. This is the fix which has to be done here, too:

https://github.com/daper/nextcloud-passwords-app/commit/4a15ba6b0bbed4e1ee21f6af4eb4f5f9156fcf88

I was unable to build the project (my build environment is to new to build it without changes), so I could not test and prepare a tested pull request.

Thank you very much in advance,
Chris

**Comment by bitterbit** [comment]
Thanks @chrbayer, I'll have a look at it soon :)

**Comment by bitterbit** [comment]
@chrbayer, Have a look at the last [release](https://github.com/bitterbit/Parse-Dashboard-Android/releases/tag/1.2.1). I have added the changes you suggested but had a really hard time testing this scenario... 

Can you test the updated apk and tell me if it works?
