### ISSUE TITLE
Ability to sort by create_at field

### ISSUE THREAD

**Issue by Tvax** [bitterbit/Parse-Dashboard-Android#5]
Sort by last insertion to the first insertion

**Comment by bitterbit** [comment]
Just made a PR to allow sorting, @Tvax let me know what you think :-)

**Comment by bitterbit** [comment]
@Tvax you can test the new feature by downloading the test release apk from [here](https://github.com/bitterbit/Parse-Dashboard-Android/releases/tag/1.2.1)  😎 . Tell me what you think

<img src="https://user-images.githubusercontent.com/4591339/55285923-2cfebc80-53c7-11e9-8f78-827206283360.png" width=200/>

**Comment by Tvax** [comment]
Really cool more than expected as we can sort by whatever field we feel like!
Good job 👌
