### ISSUE TITLE
Add insertions count 

### ISSUE THREAD

**Issue by Tvax** [bitterbit/Parse-Dashboard-Android#9]
A small one, the app would be perfect with that feature.

It would be cool to be able to see the total of insertion in a table on the homepage, right after the table name!
Like that we could see the number of users and such.

Thank you, I promise I stop bothering you after this one haha

**Comment by bitterbit** [comment]
@Tvax, no problem at all! I'm happy for interest in the project. Would you like to try and develop this feature? no pressure.. just thinking it could be fun 😃

**Comment by Tvax** [comment]
That's cool a little project for sure there's interest in it!
I get eyes strain in a minute, I didn't code for a while because of that so I would be glad to implement this feature, but I guess I won't be able to do it until I fix my eyes!
But for sure that'd be fun haha

**Comment by bitterbit** [comment]
Oh I'm sorry to hear, hope you will feel better. Maybe ill get to it later

**Comment by Tvax** [comment]
Thank you!!
Yeah no pressure thanks for your work!

**Comment by bitterbit** [comment]
Excited to see you made a PR 👑 , Great work man. I made some changes fetching is async to allow faster loading. Looking forward to seeing more issued and PRs from you 😃

**Comment by Tvax** [comment]
Thank you for merging it ! For sure will do 👍
